/* ============================================================
   המלצות נוספות — אטרקציות לילדים (3 / 7 / 10.5) ומסעדות
   נחקר ממקורות עדכניים (Google/TripAdvisor). דירוגים מקורבים.
   נטען אחרי data.js — מרחיב את window.TRIP.
   ============================================================ */
(function () {
  const T = window.TRIP;

  /* אטרקציות + מסעדות לכל אזור */
  T.recommendations = {
    milan: {
      kids: [
        { name: "Leolandia", town: "קפריאטה (~45 ד׳)", cat: "פארק שעשועים", ages: "3-10", level: "אתגר", rating: 4.6, price: "€€", q: "Leolandia, Capriate San Gervasio",
          why: "פארק ענק עם 50+ אטרקציות ודמויות אהובות — מנצח לשלושת הגילאים.", tip: "כרטיסים מראש חוסכים תור וכסף." },
        { name: "מוזיאון המדע ע\"ש לאונרדו דה וינצ׳י", town: "מילאנו", cat: "מדע", ages: "כל הגילאים", level: "כיף", rating: 4.6, price: "€€", q: "Museo Nazionale Scienza e Tecnologia Leonardo da Vinci, Milano",
          why: "מוזיאון מדע ענק עם אזורים אינטראקטיביים, צוללת אמיתית ו-Playlab לקטנים.", tip: "מצוין ליום חם — הכל ממוזג ומקורה." },
        { name: "Acquaworld", town: "קונקורצו (~30 ד׳)", cat: "פארק מים", ages: "כל הגילאים", level: "אתגר", rating: 4.3, price: "€€", q: "Acquaworld, Concorezzo",
          why: "פארק מים מקורה עם 1,100 מ׳ מגלשות, בריכת גלים ואזור לקטנים.", tip: "אידיאלי ליום חם — פתוח 10:00-20:00." },
        { name: "Hyperspace Milano", town: "מילאנו", cat: "טרמפולינות", ages: "7+", level: "אתגר", rating: 4.4, price: "€€", q: "Hyperspace Milano",
          why: "פארק טרמפולינות ענק עם מסלול נינג׳ה דו-קומתי — מושלם לבני 7 ו-10.5.", tip: "להזמין מראש; גרבי אחיזה נדרשים." },
        { name: "מוזיאון הטבע", town: "מילאנו", cat: "מוזיאון", ages: "כל הגילאים", level: "כיף", rating: 4.4, price: "€", q: "Museo Civico di Storia Naturale, Milano",
          why: "שלד טירנוזאורוס, דיורמות ופוסילים — לצד גן ציבורי למשחק.", tip: "מטרו M1 פאלסטרו; שלבו עם הגן הסמוך." },
        { name: "Highline Galleria", town: "מילאנו", cat: "הרפתקה", ages: "7+", level: "כיף", rating: 4.3, price: "€€", q: "Highline Galleria, Milano",
          why: "הליכה על גגות הגלריה עם חידות ונוף מרהיב על הדואומו.", tip: "להזמין זמן מראש; מתאים יותר לגדולים." },
        { name: "MUBA — מוזיאון הילדים", town: "מילאנו", cat: "מוזיאון ילדים", ages: "3-10", level: "כיף", rating: 4.3, price: "€€", q: "MUBA Museo dei Bambini, Milano",
          why: "מרכז אינטראקטיבי עם סדנאות יצירה ולמידה דרך עשייה.", tip: "כניסות בשעות קבועות — להזמין מראש." },
        { name: "אקווריום מילאנו", town: "מילאנו", cat: "בעלי חיים", ages: "3-10", level: "רגוע", rating: 4.2, price: "€", q: "Acquario Civico, Milano",
          why: "אקווריום נעים בלב פארק סמפיונה — אופציה קרירה לקטנים.", tip: "שלבו עם הפארק וטירת ספורצסקו." },
      ],
      food: [
        { name: "Luini Panzerotti", town: "מילאנו", meal: "צהריים", cuisine: "סטריט פוד", price: "€", per: "5-10€", rating: 4.5, q: "Luini, Via Santa Radegonda 16, Milano",
          why: "פנצרוטי מטוגן אגדי ליד הדואומו — זול, אהוב על ילדים, תור זריז." },
        { name: "Spontini", town: "מילאנו", meal: "צהריים", cuisine: "פיצה", price: "€", per: "8-15€", rating: 4.3, q: "Pizzeria Spontini, Milano",
          why: "פיצה עבה ועסיסי במשקל — מהיר וקל לילדים." },
        { name: "Sorbillo Lievito Madre al Duomo", town: "מילאנו", meal: "ערב", cuisine: "פיצה", price: "€€", per: "15-25€", rating: 4.3, q: "Gino Sorbillo Lievito Madre al Duomo, Milano",
          why: "פיצה נפוליטנית קלאסית עם בצק אוורירי, צעד מהדואומו." },
        { name: "Trattoria Milanese", town: "מילאנו", meal: "ערב", cuisine: "איטלקי", price: "€€", per: "25-35€", rating: 4.4, q: "Trattoria Milanese, Milano",
          why: "טרטוריה מסורתית במרכז ההיסטורי — מטבח מילאנזי אותנטי." },
        { name: "Obicà Mozzarella Bar", town: "מילאנו", meal: "צהריים", cuisine: "איטלקי", price: "€€", per: "20-30€", rating: 4.3, q: "Obica Mozzarella Bar, Duomo, Milano",
          why: "מוצרלה טרייה, פסטות ופיצה מול הדואומו — מנות פשוטות שילדים אוהבים." },
        { name: "Princi", town: "מילאנו", meal: "בוקר", cuisine: "מאפייה", price: "€", per: "5-12€", rating: 4.4, q: "Princi, Milano centro",
          why: "מאפייה מעולה — קרואסונים ומאפים טריים לבוקר מהיר." },
        { name: "Camparino in Galleria", town: "מילאנו", meal: "בוקר", cuisine: "קפה", price: "€€", per: "10-20€", rating: 4.4, q: "Camparino in Galleria, Milano",
          why: "קפה היסטורי מ-1915 בגלריה — קפוצ׳ינו עם נוף לפיאצה." },
        { name: "Artico Gelateria", town: "מילאנו", meal: "כללי", cuisine: "גלידה", price: "€", per: "4-8€", rating: 4.6, q: "Artico Gelateria, Milano",
          why: "מהגלידריות הטובות במילאנו — פינוק חובה בחום." },
      ],
    },

    garda: {
      kids: [
        { name: "Caneva Aquapark", town: "לאזיסה", cat: "פארק מים", ages: "כל הגילאים", level: "אתגר", rating: 4.2, price: "€€€", q: "Caneva The Aquapark, Lazise",
          why: "פארק מים תמטי ענק עם מגלשות אדרנלין וגם אזורי שחייה רגועים לקטנים.", tip: "כרטיס משולב עם Movieland חוסך כסף." },
        { name: "Movieland Park", town: "לאזיסה", cat: "פארק שעשועים", ages: "כל הגילאים", level: "כיף", rating: 4.3, price: "€€€", q: "Movieland Park, Lazise",
          why: "פארק קולנוע עם מתקנים, מופעי פעלולים חיים ואזור משפחתי לקטנים.", tip: "תכננו את היום סביב מופעי הפעלולים." },
        { name: "Parco Natura Viva", town: "בוסולנגו", cat: "ספארי", ages: "כל הגילאים", level: "כיף", rating: 4.4, price: "€€", q: "Parco Natura Viva, Bussolengo",
          why: "ספארי ברכב בין אריות וג׳ירפות + פארק דינוזאורים שילדים מתים עליו.", tip: "להקדיש 4-5 שעות; כרטיסים מראש." },
        { name: "Jungle Adventure Park", town: "פסקיירה", cat: "פארק חבלים", ages: "3-10", level: "אתגר", rating: 4.5, price: "€€", q: "Jungle Adventure Park, Peschiera del Garda",
          why: "פארק חבלים ביער עם אומגות וגשרים — מסלולים נפרדים לקטנים ולגדולים.", tip: "נעליים סגורות חובה." },
        { name: "שייט מפסקיירה לסירמיונה", town: "פסקיירה", cat: "שייט", ages: "כל הגילאים", level: "כיף", rating: 4.6, price: "€€€", q: "Peschiera del Garda Port",
          why: "שייט בחוף הדרומי עם עצירת רחצה מהסירה — הילדים אפילו מקבלים להגה.", tip: "להביא בגד ים ומגבת." },
        { name: "סירמיונה + חוף Jamaica", town: "סירמיונה", cat: "חוף + טירה", ages: "כל הגילאים", level: "רגוע", rating: 4.5, price: "€", q: "Jamaica Beach, Sirmione",
          why: "מצודה על המים + חוף עם מים רדודים וסלעים שטוחים מושלמים למשפחות.", tip: "להגיע מוקדם; נעלי מים מומלצות." },
        { name: "Rimbalzello Adventure", town: "סאלו", cat: "פארק חבלים", ages: "3-10", level: "אתגר", rating: 4.6, price: "€€", q: "Rimbalzello Adventure, Salo",
          why: "5 מסלולי חבלים בעצים בדרגות קושי — מהנמוך לקטנים ועד 15 מ׳ לגדולים.", tip: "להזמין מראש בקיץ." },
        { name: "Legoland Water Park", town: "קסטלנואובו", cat: "פארק מים", ages: "3-10", level: "כיף", rating: 4.3, price: "€€€", q: "Legoland Water Park, Castelnuovo del Garda",
          why: "פארק מים בנושא לגו עם נהר הרפתקאות ובריכות רדודות — מושלם לטווח הגילאים.", tip: "אם בגרדהלנד — אפשר לשלב יום מים כאן." },
      ],
      food: [
        { name: "L'Artigiano dei Sapori", town: "לאזיסה", meal: "בוקר", cuisine: "קפה+גלידה", price: "€", per: "5-12€", rating: 4.6, q: "L'Artigiano dei Sapori Gelato, Lazise",
          why: "קפה וקרואסונים לבוקר וגלידה מעולה אחר כך — בלב לאזיסה." },
        { name: "Pit Stop Lazise", town: "לאזיסה", meal: "צהריים", cuisine: "פיצה", price: "€€", per: "12-25€", rating: 4.5, q: "Pit Stop Lazise, Lazise",
          why: "פיצה דקה מעולה וישיבה מול התנור — אהוב על ילדים." },
        { name: "George Fish & Chips", town: "לאזיסה", meal: "צהריים", cuisine: "דגים", price: "€€", per: "12-22€", rating: 4.5, q: "George Fish & Chips, Lazise",
          why: "פיש אנד צ׳יפס איכותי במחיר הוגן — מהיר ואהוב על הילדים." },
        { name: "La Kambusa", town: "לאזיסה", meal: "ערב", cuisine: "דגי אגם", price: "€€€", per: "30-50€", rating: 4.5, q: "Ristorante La Kambusa, Lazise",
          why: "מסעדה כפרית בבניין מהמאה ה-12 עם דגים על הגריל." },
        { name: "Alla Grotta", town: "לאזיסה", meal: "ערב", cuisine: "דגי אגם", price: "€€€", per: "30-50€", rating: 4.4, q: "Ristorante alla Grotta, Lazise",
          why: "מנות קלאסיות מול הנמל — מיקום נופי על המים." },
        { name: "La Piccola Osteria", town: "ברדולינו", meal: "צהריים", cuisine: "איטלקי", price: "€€", per: "20-35€", rating: 4.6, q: "La Piccola Osteria, Bardolino",
          why: "פסטות ודגי אגם בסמטה מקסימה — אווירה משפחתית חמה." },
        { name: "Osteria Due Nani", town: "ברדולינו", meal: "ערב", cuisine: "דגי אגם", price: "€€€", per: "30-45€", rating: 4.5, q: "Osteria Due Nani, Bardolino",
          why: "פנינה על הטיילת עם מנות דגי אגם אותנטיות ונוף לאגם." },
        { name: "Gelateria Biancaneve", town: "ברדולינו", meal: "כללי", cuisine: "גלידה", price: "€", per: "4-9€", rating: 4.6, q: "Gelateria Biancaneve, Bardolino",
          why: "נחשבת לגלידה הכי טובה באזור האגם — קינוח חובה." },
      ],
    },

    dolomites: {
      kids: [
        { name: "רכבל Col Raiser", town: "סנטה כריסטינה", cat: "רכבל", ages: "כל הגילאים", level: "כיף", rating: 4.6, price: "€€", q: "Col Raiser cable car, Santa Cristina Valgardena",
          why: "רכבל מרהיב למרגלות פסגות האודלה עם מסלולים קלים ובקתות.", tip: "Gardena Card משתלם אם תשתמשו ברכבלים כמה ימים." },
        { name: "רכבל Seceda", town: "אורטיזיי", cat: "רכבל", ages: "כל הגילאים", level: "אתגר", rating: 4.8, price: "€€€", q: "Seceda cable car, Ortisei",
          why: "עלייה לרכס הסצדה האייקוני (2,500 מ׳) עם נוף דרמטי שמרשים גם גדולים.", tip: "בקיץ חובה הזמנה מראש עם חלון זמן; שכבות חמות." },
        { name: "Alpe di Siusi (Mont Sëuc)", town: "אורטיזיי", cat: "רכבל + רמה", ages: "כל הגילאים", level: "כיף", rating: 4.7, price: "€€", q: "Mont Seuc cable car, Ortisei",
          why: "רכבל לרמה האלפינית הגדולה באירופה — מגרש משחקים ושבילים פתוחים.", tip: "ילדים עד 8 חינם; אפשר עם עגלה." },
        { name: "שביל המכשפות (Sentiero delle Streghe)", town: "Alpe di Siusi", cat: "הרפתקה", ages: "3-10", level: "כיף", rating: 4.6, price: "חינם", q: "Sentiero delle Streghe, Alpe di Siusi",
          why: "שביל קסום בנושא מכשפות עם פסלי עץ, בית עץ ואתגרי מיומנות.", tip: "לולאה קצרה לקטנים, ארוכה (~שעתיים) לגדולים." },
        { name: "פוניקולר Resciesa", town: "אורטיזיי", cat: "רכבל", ages: "כל הגילאים", level: "כיף", rating: 4.5, price: "€€", q: "Funicolare Resciesa, Ortisei",
          why: "פוניקולר תלול ל-2,200 מ׳ עם נוף עוצר נשימה ושבילים נינוחים.", tip: "בקתת הר בפסגה למנוחה ואוכל." },
        { name: "Alpine Coaster Gardonè", town: "פרדאצו (~50 ד׳)", cat: "מגלשת הרים", ages: "7+", level: "אקסטרים", rating: 4.6, price: "€€", q: "Alpine Coaster Gardone, Predazzo",
          why: "מגלשת הרים מהירה של 900+ מ׳ עם פניות 360° ביער — ריגוש לגדולים.", tip: "מינ׳ גובה 105 ס\"מ; 105-135 ס\"מ עם מלווה." },
        { name: "Trail Arena (Bike Park)", town: "סלבה", cat: "אופני הרים", ages: "7+", level: "אתגר", rating: 4.4, price: "€€", q: "Trail Arena Dantercepies, Selva di Val Gardena",
          why: "פארק אופניים עם מסלולי flow פנורמיים — אדרנלין לרוכבים הצעירים.", tip: "אפשר השכרת אופניים; עד גיל 8 חינם." },
        { name: "אגם Carezza (Karersee)", town: "נובה לבנטה (~40 ד׳)", cat: "אגם", ages: "כל הגילאים", level: "רגוע", rating: 4.6, price: "חינם", q: "Lago di Carezza, Nova Levante",
          why: "אגם הרים אגדי בצבעי קשת עם שביל היקפי קצר ונוף לרוזנגרטן.", tip: "להגיע בבוקר מוקדם; שחייה אסורה." },
      ],
      food: [
        { name: "Rifugio Firenze", town: "על ההר", meal: "צהריים", cuisine: "בקתה אלפינית", price: "€€", per: "15-30€", rating: 4.6, q: "Rifugio Firenze Regensburgerhütte, Santa Cristina",
          why: "בקתת הר בהליכה קלה מרכבל Col Raiser, עם קנדרלי וטרסה שטופת שמש." },
        { name: "Malga Sanon", town: "Alpe di Siusi", meal: "צהריים", cuisine: "בקתה אלפינית", price: "€€", per: "15-30€", rating: 4.6, q: "Malga Sanon, Alpe di Siusi",
          why: "חוות חלב אלפינית עם מוצרי חלב מעולים וקייזרשמארן מהטובים באזור." },
        { name: "Rifugio Sasso Piatto", town: "Alpe di Siusi", meal: "צהריים", cuisine: "טירולי", price: "€€", per: "18-32€", rating: 4.5, q: "Rifugio Sasso Piatto Plattkofelhütte, Alpe di Siusi",
          why: "בקתה פופולרית עם נוף 360° ואוכל ביתי משובח." },
        { name: "La Tambra", town: "סנטה כריסטינה", meal: "ערב", cuisine: "פיצה+סטייק", price: "€€", per: "20-40€", rating: 4.5, q: "La Tambra, Santa Cristina Valgardena",
          why: "פיצה מתנור עצים וסטייקים על גריל פחמים — אווירת עץ חמימה." },
        { name: "Pizzeria Da Peppi", town: "סנטה כריסטינה", meal: "ערב", cuisine: "איטלקי", price: "€€", per: "15-30€", rating: 4.4, q: "Pizzeria Da Peppi, Santa Cristina Valgardena",
          why: "מועדף מקומי עם מבחר פיצות רחב ומחירים הוגנים." },
        { name: "Mauriz Keller", town: "אורטיזיי", meal: "ערב", cuisine: "טירולי", price: "€€€", per: "25-45€", rating: 4.6, q: "Mauriz Keller, Ortisei",
          why: "פונדק בן מאות שנים במדרחוב עם מטבח דרום-טירולי ופיצות מתנור עצים." },
        { name: "Mar Dolomit", town: "אורטיזיי", meal: "כללי", cuisine: "פיצה", price: "€€", per: "18-35€", rating: 4.4, q: "Mar Dolomit, Ortisei",
          why: "במרכז אורטיזיי עם טרסה פנורמית — מיקום נוח מאוד למשפחות." },
        { name: "La Cort My Dollhouse", town: "אורטיזיי", meal: "בוקר", cuisine: "בית קפה", price: "€€", per: "10-20€", rating: 4.5, q: "La Cort My Dollhouse, Ortisei",
          why: "בר-קפה-מאפייה עם מאפים טריים, גלידה ביתית ואופציות ללא גלוטן." },
      ],
    },

    verona: {
      kids: [
        { name: "Gardaland Resort", town: "קסטלנואובו (~30 ד׳)", cat: "פארק שעשועים", ages: "כל הגילאים", level: "אתגר", rating: 4.5, price: "€€€", q: "Gardaland Park, Castelnuovo del Garda",
          why: "פארק השעשועים הגדול באיטליה — 40 אטרקציות + אזור פפה פיג לקטנים.", tip: "להגיע בפתיחה ולהתחיל מהרכבות הפופולריות." },
        { name: "Parco Natura Viva", town: "בוסולנגו (~20 ד׳)", cat: "ספארי", ages: "כל הגילאים", level: "כיף", rating: 4.4, price: "€€", q: "Parco Natura Viva, Bussolengo",
          why: "ספארי ברכב בין ג׳ירפות וקרנפים + גן חיות הליכה ומגרשי משחק.", tip: "שטח גבעי — שקלו מנשא לבן ה-3." },
        { name: "Parco Giardino Sigurtà", town: "ולג׳ו (~30 ד׳)", cat: "פארק ענק", ages: "כל הגילאים", level: "רגוע", rating: 4.6, price: "€€", q: "Parco Giardino Sigurtà, Valeggio sul Mincio",
          why: "מהגנים היפים באירופה עם מבוך ענק, חוות חיות ומדשאות לריצה.", tip: "קחו את הרכבת הפנימית ואל תפספסו את המבוך." },
        { name: "Torre dei Lamberti", town: "ורונה", cat: "מגדל תצפית", ages: "כל הגילאים", level: "אתגר", rating: 4.4, price: "€", q: "Torre dei Lamberti, Verona",
          why: "המגדל הגבוה בעיר (84 מ׳) — 368 מדרגות או מעלית זכוכית, תצפית 360°.", tip: "הגדולים יכולים לטפס; עם הקטן קחו מעלית." },
        { name: "פוניקולר Castel San Pietro", town: "ורונה", cat: "רכבל", ages: "כל הגילאים", level: "כיף", rating: 4.5, price: "€", q: "Funicolare di Castel San Pietro, Verona",
          why: "רכבל קצר שמטפס בדקה לתצפית הכי יפה על העיר העתיקה.", tip: "שלבו עם גלידה למעלה לקראת שקיעה." },
        { name: "מוזיאון הטבע", town: "ורונה", cat: "מוזיאון", ages: "3-10", level: "רגוע", rating: 4.2, price: "€", q: "Museo di Storia Naturale, Verona",
          why: "מאובנים, דינוזאורים ומציאות רבודה — מקלט נעים משעות החום.", tip: "סגור בימי שני; בדקו פעילויות לילדים מראש." },
        { name: "Caneva Aquapark", town: "לאזיסה (~30 ד׳)", cat: "פארק מים", ages: "כל הגילאים", level: "אתגר", rating: 4.3, price: "€€€", q: "Caneva The Aquapark, Lazise",
          why: "פארק מים קריבי ענק — אידיאלי ליום קיץ חם.", tip: "יש אזור בריכה רדודה לבן ה-3." },
        { name: "Casa di Giulietta", town: "ורונה", cat: "אתר היסטורי", ages: "7+", level: "רגוע", rating: 4.0, price: "€€", q: "Casa di Giulietta, Verona",
          why: "המרפסת של יוליה וקיר מכתבי האהבה — סיפור שייקספיר חי במרכז.", tip: "החצר חינם; לכניסה כדאי כרטיס מראש." },
      ],
      food: [
        { name: "Caffè Borsari", town: "ורונה", meal: "בוקר", cuisine: "קפה", price: "€", per: "3-8€", rating: 4.5, q: "Caffè Borsari, Verona",
          why: "בית קפה היסטורי קטנטן — קפוצ׳ינו וקורנטו לפתיחת בוקר אותנטית." },
        { name: "La Lanterna", town: "ורונה", meal: "צהריים", cuisine: "איטלקי", price: "€€", per: "15-25€", rating: 4.3, q: "La Lanterna, Verona",
          why: "פיצה ופסטה ביתית ליד פיאצה ברה — כיסאות תינוק ומנות לילדים." },
        { name: "Ristorante Greppia", town: "ורונה", meal: "צהריים", cuisine: "איטלקי", price: "€€", per: "20-35€", rating: 4.2, q: "Ristorante Greppia, Verona",
          why: "מטבח ורונזי מסורתי באווירה משפחתית — אפשר פסטה פשוטה לפעוטות." },
        { name: "Pizzeria du de Cope", town: "ורונה", meal: "ערב", cuisine: "פיצה", price: "€€", per: "12-22€", rating: 4.4, q: "Pizzeria du de Cope, Verona",
          why: "פיצריה תוססת ומוערכת עם פיצות גדולות וטריות — אידיאלית למשפחה." },
        { name: "Trattoria al Pompiere", town: "ורונה", meal: "ערב", cuisine: "איטלקי", price: "€€€", per: "30-45€", rating: 4.4, q: "Trattoria al Pompiere, Verona",
          why: "טרטוריה ותיקה ומקסימה עם פסטות כפריות ומבחר גבינות ונקניקים." },
        { name: "Nastro Azzurro", town: "ורונה", meal: "ערב", cuisine: "פיצה", price: "€€", per: "12-20€", rating: 4.2, q: "Nastro Azzurro, Piazza Bra Verona",
          why: "פיצריה בפיאצה ברה עם תפריט נרחב, מחירים הוגנים וצוות אדיב לילדים." },
        { name: "Gelateria Savoia", town: "ורונה", meal: "כללי", cuisine: "גלידה", price: "€", per: "3-6€", rating: 4.5, q: "Gelateria Savoia, Verona",
          why: "גלידרייה אגדית מ-1939 — להיט הפינגווינים על מקל בקרב ילדים." },
        { name: "Venchi Cioccolato e Gelato", town: "ורונה", meal: "כללי", cuisine: "שוקולד+גלידה", price: "€€", per: "4-8€", rating: 4.5, q: "Venchi, Verona Arena",
          why: "שוקולד וגלידה ליד הארנה — שילוב שהילדים אוהבים." },
      ],
    },
  };

  /* מסעדות לכל יום (בוקר / צהריים / ערב). דירוג ומחיר מקורבים. */
  T.meals = {
    "2026-08-13": [
      { meal: "ערב", name: "ארוחה קלה בדרך / ליד הדירה", note: "נחיתה מאוחרת (21:40) — משהו קליל בדרך לדירה." },
    ],
    "2026-08-14": [
      { meal: "בוקר", name: "Princi", town: "מילאנו", price: "€", rating: 4.4, q: "Princi, Milano centro" },
      { meal: "צהריים", name: "Luini Panzerotti", town: "ליד הדואומו", price: "€", rating: 4.5, q: "Luini, Via Santa Radegonda 16, Milano" },
      { meal: "ערב", name: "Sorbillo (פיצה) + גלידת Artico", town: "מילאנו", price: "€€", rating: 4.3, q: "Gino Sorbillo Lievito Madre al Duomo, Milano" },
    ],
    "2026-08-15": [
      { meal: "בוקר", name: "Camparino in Galleria", town: "מילאנו", price: "€€", rating: 4.4, q: "Camparino in Galleria, Milano" },
      { meal: "צהריים", name: "Pit Stop (פיצה)", town: "לאזיסה", price: "€€", rating: 4.5, q: "Pit Stop Lazise, Lazise" },
      { meal: "ערב", name: "La Kambusa (דגי אגם)", town: "לאזיסה", price: "€€€", rating: 4.5, q: "Ristorante La Kambusa, Lazise" },
    ],
    "2026-08-16": [
      { meal: "בוקר", name: "L'Artigiano dei Sapori", town: "לאזיסה", price: "€", rating: 4.6, q: "L'Artigiano dei Sapori Gelato, Lazise" },
      { meal: "צהריים", name: "אוכל בתוך גרדהלנד", note: "מסעדות ודוכנים בפארק — או פיקניק." },
      { meal: "ערב", name: "George Fish & Chips", town: "לאזיסה", price: "€€", rating: 4.5, q: "George Fish & Chips, Lazise" },
    ],
    "2026-08-17": [
      { meal: "בוקר", name: "קפה במרכז לאזיסה", town: "לאזיסה", price: "€", rating: 4.5, q: "L'Artigiano dei Sapori Gelato, Lazise" },
      { meal: "צהריים", name: "La Piccola Osteria", town: "ברדולינו", price: "€€", rating: 4.6, q: "La Piccola Osteria, Bardolino" },
      { meal: "ערב", name: "Osteria Due Nani + גלידת Biancaneve", town: "ברדולינו", price: "€€€", rating: 4.5, q: "Osteria Due Nani, Bardolino" },
    ],
    "2026-08-18": [
      { meal: "בוקר", name: "מאפים בדירה / קפה מקומי", town: "לאזיסה", price: "€", q: "Lazise centro" },
      { meal: "צהריים", name: "George Fish & Chips", town: "לאזיסה", price: "€€", rating: 4.5, q: "George Fish & Chips, Lazise" },
      { meal: "ערב", name: "Alla Grotta (מול הנמל)", town: "לאזיסה", price: "€€€", rating: 4.4, q: "Ristorante alla Grotta, Lazise" },
    ],
    "2026-08-19": [
      { meal: "בוקר", name: "קפה אחרון בלאזיסה", town: "לאזיסה", price: "€", q: "Lazise centro" },
      { meal: "צהריים", name: "עצירה בדרך / עיירה אלפינית", note: "ארוחה קלה בעצירה בדרך להרים." },
      { meal: "ערב", name: "La Tambra (פיצה+סטייק)", town: "סנטה כריסטינה", price: "€€", rating: 4.5, q: "La Tambra, Santa Cristina Valgardena" },
    ],
    "2026-08-20": [
      { meal: "בוקר", name: "ארוחת בוקר במלון Touring", note: "כלולה בלינה." },
      { meal: "צהריים", name: "Rifugio Firenze (בקתת הר)", town: "על ההר", price: "€€", rating: 4.6, q: "Rifugio Firenze Regensburgerhütte, Santa Cristina" },
      { meal: "ערב", name: "Pizzeria Da Peppi", town: "סנטה כריסטינה", price: "€€", rating: 4.4, q: "Pizzeria Da Peppi, Santa Cristina Valgardena" },
    ],
    "2026-08-21": [
      { meal: "בוקר", name: "ארוחת בוקר במלון Touring", note: "כלולה בלינה." },
      { meal: "צהריים", name: "Malga Sanon (Alpe di Siusi)", town: "על ההר", price: "€€", rating: 4.6, q: "Malga Sanon, Alpe di Siusi" },
      { meal: "ערב", name: "Mauriz Keller", town: "אורטיזיי", price: "€€€", rating: 4.6, q: "Mauriz Keller, Ortisei" },
    ],
    "2026-08-22": [
      { meal: "בוקר", name: "ארוחת בוקר במלון Touring", note: "כלולה בלינה." },
      { meal: "צהריים", name: "Rifugio Sasso Piatto", town: "Alpe di Siusi", price: "€€", rating: 4.5, q: "Rifugio Sasso Piatto Plattkofelhütte, Alpe di Siusi" },
      { meal: "ערב", name: "La Tambra", town: "סנטה כריסטינה", price: "€€", rating: 4.5, q: "La Tambra, Santa Cristina Valgardena" },
    ],
    "2026-08-23": [
      { meal: "בוקר", name: "ארוחת בוקר במלון Touring", note: "כלולה בלינה." },
      { meal: "צהריים", name: "עצירה בדרך לוורונה", note: "ארוחה קלה בדרך." },
      { meal: "ערב", name: "Pizzeria du de Cope + גלידת Savoia", town: "ורונה", price: "€€", rating: 4.4, q: "Pizzeria du de Cope, Verona" },
    ],
    "2026-08-24": [
      { meal: "בוקר", name: "Caffè Borsari", town: "ורונה", price: "€", rating: 4.5, q: "Caffè Borsari, Verona" },
      { meal: "צהריים", name: "La Lanterna", town: "ליד פיאצה ברה", price: "€€", rating: 4.3, q: "La Lanterna, Verona" },
      { meal: "ערב", name: "Trattoria al Pompiere", town: "ורונה", price: "€€€", rating: 4.4, q: "Trattoria al Pompiere, Verona" },
    ],
    "2026-08-25": [
      { meal: "בוקר", name: "Caffè Borsari", town: "ורונה", price: "€", rating: 4.5, q: "Caffè Borsari, Verona" },
      { meal: "צהריים", name: "ארוחה קלה בדרך לשדה התעופה", note: "לפני החזרת הרכב והטיסה." },
    ],
  };
})();
